import 'dotenv/config';
import express from 'express';
import {
  Client,
  GatewayIntentBits,
  Events,
  EmbedBuilder,
  ActionRowBuilder,
  ButtonBuilder,
  ButtonStyle,
  ModalBuilder,
  TextInputBuilder,
  TextInputStyle
} from 'discord.js';
import { load, save } from './store.js';
import { isOwner, panelEmbed, panelRows } from './panelFlows.js';

const { TOKEN, OWNER_ID, PORT = 3000 } = process.env;

// === Keepalive for Render ===
const app = express();
app.get('/', (_, res) => res.status(200).send('OK'));
app.listen(PORT, () => console.log(`Keepalive on :${PORT}`));

// === Discord client ===
const client = new Client({ intents: [GatewayIntentBits.Guilds] });
client.once(Events.ClientReady, (c) => console.log(`✅ Logged in as ${c.user.tag}`));

// === Interaction handler ===
client.on(Events.InteractionCreate, async (interaction) => {
  try {
    // Slash command: /panel
    if (interaction.isChatInputCommand() && interaction.commandName === 'panel') {
      if (!isOwner(interaction, OWNER_ID))
        return interaction.reply({ content: 'Owner only.', ephemeral: true });

      await interaction.reply({
        embeds: [panelEmbed()],
        components: panelRows(),
        ephemeral: true
      });
      return;
    }

    // Slash command: /cmd run
    if (interaction.isChatInputCommand() && interaction.commandName === 'cmd') {
      const sub = interaction.options.getSubcommand();
      if (sub === 'run') {
        const store = load('commands.json');
        const name = interaction.options.getString('name');
        const found = store.commands.find((c) => c.name === name);
        if (!found)
          return interaction.reply({ content: 'Command not found.', ephemeral: true });

        if (found.type === 'text')
          return interaction.reply({ content: found.payload });

        if (found.type === 'embed') {
          const eStore = load('embeds.json');
          const eb = eStore.embeds.find((e) => e.key === found.payload);
          if (!eb)
            return interaction.reply({
              content: 'Embed not found for this command.',
              ephemeral: true
            });
          return interaction.reply({
            embeds: [new EmbedBuilder(eb.embed)],
            components: eb.components?.length
              ? eb.components.map((r) => ({ ...r }))
              : []
          });
        }
      }
      return;
    }

    // === Button clicks ===
    if (interaction.isButton()) {
      if (!isOwner(interaction, OWNER_ID))
        return interaction.reply({ content: 'Owner only.', ephemeral: true });

      const id = interaction.customId;

      // Button: Create Command → Open modal
      if (id === 'create_command') {
        const modal = new ModalBuilder()
          .setCustomId('modal_create_command')
          .setTitle('🧩 Create a Custom Command')
          .addComponents(
            new ActionRowBuilder().addComponents(
              new TextInputBuilder()
                .setCustomId('cmd_name')
                .setLabel('Command Name')
                .setPlaceholder('e.g. greet')
                .setRequired(true)
                .setStyle(TextInputStyle.Short)
            ),
            new ActionRowBuilder().addComponents(
              new TextInputBuilder()
                .setCustomId('cmd_type')
                .setLabel('Type (text / embed)')
                .setPlaceholder('text')
                .setRequired(true)
                .setStyle(TextInputStyle.Short)
            ),
            new ActionRowBuilder().addComponents(
              new TextInputBuilder()
                .setCustomId('cmd_payload')
                .setLabel('Payload (message or embed key)')
                .setPlaceholder('e.g. Hello there!')
                .setRequired(true)
                .setStyle(TextInputStyle.Paragraph)
            )
          );
        return interaction.showModal(modal);
      }

      // Button: List commands
      if (id === 'list_commands') {
        const store = load('commands.json');
        const list =
          store.commands.map((c) => `• **${c.name}** — ${c.type}`).join('\n') ||
          'No commands yet.';
        return interaction.reply({ content: list, ephemeral: true });
      }

      // Button: Make Embed (simple demo embed)
      if (id === 'make_embed') {
        const embed = new EmbedBuilder()
          .setTitle('Example Embed')
          .setDescription('🪄 This is a test embed generated by the panel.')
          .setColor(0x5865f2);
        return interaction.reply({ embeds: [embed], ephemeral: true });
      }

      return interaction.reply({
        content: `Clicked unknown button: ${id}`,
        ephemeral: true
      });
    }

    // === Modal Submit: Create Command ===
    if (interaction.isModalSubmit()) {
      if (interaction.customId === 'modal_create_command') {
        const name = interaction.fields.getTextInputValue('cmd_name').trim();
        const type = interaction.fields.getTextInputValue('cmd_type').trim().toLowerCase();
        const payload = interaction.fields.getTextInputValue('cmd_payload').trim();

        const store = load('commands.json');
        const exists = store.commands.find((c) => c.name === name);
        if (exists)
          return interaction.reply({ content: '❌ Command name already exists.', ephemeral: true });

        store.commands.push({ name, type, payload });
        save('commands.json', store);

        await interaction.reply({
          content: `✅ Command **${name}** (${type}) created successfully!`,
          ephemeral: true
        });
      }
    }
  } catch (err) {
    console.error('❌ Interaction error:', err);
    if (interaction.isRepliable())
      await interaction.reply({ content: 'Something went wrong.', ephemeral: true });
  }
});

client.login(TOKEN);
